server:
  ip: localhost
  port: 5555

spring:
   datasource:
     name: user
     url: jdbc:mysql://localhost/lottery?useUnicode=true&characterEncoding=utf-8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
   freemarker:
     prefix: ftl/
     cache: false
   mail:
     host: smtp.163.com
     username: xuzhiqing2014@163.com
     password: W285165W
     properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#   http:
#       multipart:
#         enabled: true
#         max-file-size: 20MB
#         max-request-size: 200MB
redis:
  host: localhost
  port: 6379
  timeout: 5000
  pool:
    minIdle: 10
    maxIdle: 10
    maxTotal: 100
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true

mybatis:
  check-config-location: true
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.finance.lottery.entity

football:
  redis:
    admin:
      index:
        visit-count-key: 'visit_count'
    user:
      resetpass:
        prefix: resetpass_
        timeout:
          day:
          hour: 6
          minite:
          second:
        email:
          subject: 密码重置
          htmlTemplate: '<div style="padding: 10px;">
                        <div style="padding: 2px;font-size: 1.3vw">
                            <p>尊敬的 %s 您好，您正在使用重置密码功能，请点击 <a href="%s">重置密码</a> 完成密码重置。</p>
                        </div>
                        <div style="padding: 2px">
                            <ul style="color: rgb(169, 169, 189);font-size: 1.2vw">
                                <li>为了保障您帐号的安全，该链接有效期为12小时。</li>
                                <li>该链接只能使用一次，请周知。</li>
                                <li>如果该链接无法点击，请直接复制以上网址到浏览器地址栏中访问。</li>
                                <li>请您妥善保管，此邮件无需回复。</li>
                            </ul>
                        </div>
                     </div>'



lottery:
  bigdata:
    url: http://www.dongqiudi.com/data
    dqdWebsite: http://www.dongqiudi.com/
    statListCssPath: '#stat_list'
    statDetailCssPath: '#stat_detail'
  live:
    netease:
      url: http://live.caipiao.163.com
    matchs:
      url: http://api.caipiao.163.com/jjc_live.html?gameEn=jczq
      params:
        gameEn: jczq
        product: caipiao_client
        mobileType: iphone
        ver: 4.33
        channel: appstore
        apiVer: 1.1
        apiLevel: 27
        deviceId: 070878BD-3122-4B1C-B113-B724E1D4C27C
    matchinfo:
      url: http://api.caipiao.163.com/biFen_matchDetail.html?hostId={hostId}&matchId={matchId}&type={type}&visitId={visitId}
      oddurl: http://api.caipiao.163.com/biFen_matchDetailOdds.html?hostId={hostId}&matchId={matchId}&type=13&visitId={visitId}
      params:
        gameEn: jczq
        product: caipiao_client
        mobileType: iphone
        ver: 4.33
        channel: appstore
        apiVer: 1.1
        apiLevel: 27
        deviceId: 070878BD-3122-4B1C-B113-B724E1D4C27C
  information:
    matchs:
      url: 'http://www.cubegoal.com/cube/index-%s-%s.html'
      cssPath: '.m-mflist .mfcell'
    detail:
      url: 'http://www.cubegoal.com%s'
      cssPath: '#team'
  index:
    url: 'http://live.aicai.com/jsbf/timelyscore!dynamicBfDataFromPage.htm?lotteryType=zc&issue=%s'
    jsonPath: '$.result.bf_page'
    cssPath: '.md_data_box'
#    matchs:https://www.cubegoal.com/cube/index-2018-05-30-0-1.html
#      url: http://app.huanhuba.com/app/zqmf/index?sign={sign}&data={data}
#      infoJsonPath: $.data
#      params:
#        sign1: 7a0d7465a1643b278709be92a45d3a67
#        sign: cb0d0737322fc7a8c9decf864f31d159
#        template: '{"login_id":"586437","versionNum":"3.03","mf_token":"08b5be23b7f93b52508682133e4a3f3ec2f58f63","iostype":"8","platform":"ios","datetime":"%s","page":"%s","idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC"}'
##        data: '{"login_id":"586437","versionNum":"3.03","mf_token":"08b5be23b7f93b52508682133e4a3f3ec2f58f63","iostype":"8","platform":"ios","datetime":"%s","page":"%s","idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC"}'
#        data1: '{"datetime":"%s","page":"%s","idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC","iostype":"8","versionNum":"3.03","platform":"ios"}'
#    detail:https://www.cubegoal.com/cube/2786859.html
#      url:  http://app.huanhuba.com/app/Analyze/game20in1?sign={sign}&data={data}
#      infoJsonPath: $.data.zqmf_detail.data
#      params:
#        sign: fbf6d4161217c559f6fcb8ee2d121ba7
#        data: '{"idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC","match_id":%s,"iostype":"8","versionNum":"3.03","platform":"ios"}'
  football:
    new:
      url: http://api.dongqiudi.com/app/tabs/iphone/58.json?mark=gif&version=600
  recommend:
    matchs:
      url: http://app.huanhuba.com/app/market/cBoxStep1?data={data}&sign={sign}
      params:
        data: '{"versionNum":"3.34","winy_token":"672480f5684b908e4ea4ba67fb96fc158d7682e5b3cd434b44bcac92ae36aa74","dt":"2","mf_token":"541306c51fe1c178322800dd3114e4612906e5e9","platform":"ios","login_id":"586437","iostype":"12","page":%s,"idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC"}'
        sign: e954f0e5e5905d3349f5bf21a795dddd
    details:
      url: http://app.huanhuba.com/app/Market/cBoxStep2New?data={data}&sign={sign}
      params:
        data: '{"dt":"2","login_id":"586437","versionNum":"3.34","match_id":%s,"platform":"ios","user_id":"586437","iostype":"12","idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC"}'
        sign: dfcbe8ecd8b91c70bcafb72d46edb72d
    result:
      url: http://app.huanhuba.com/app/scorev2/match_detail_new?data={data}&sign={sign}
      params:
        data: '{"winy_token":"0e661d3e61e37ba511156a63f0ed489a10bd84f4ec737cd7c77dac88d2ce44c3","versionNum":"3.34","dt":"2","mf_token":"0f269386f2c1f95c4ab0997a0a5ed7b797e3f6f4","login_id":"586437","platform":"ios","match_id":"%s","iostype":"12","type":"1","idfa":"BB681EA3-C227-45BE-8E30-F5ED29ACA2BC"}'
        sign: 5ababe588e680052668a76c11dddf385
logging:
  level:
    org:
      springframework:
        web: ERROR

#redis key
count:
  visit:
    total: count_visit_total
    football-news: count_visit_footballnews
    match-analysis: count_visit_match_analysis
    score-live: count_visit_score_live
    big-data: count_visit_big_data
  newuser:
    total: count_newuser_total
    common: count_newuser_common
    senior: count_newuser_senior
    finance: count_newuser_finance
  recharge:
    total: count_recharge_total
    common: count_recharge_common
    senior: count_recharge_senior
    finance: count_recharge_finance
  withdraw:
    total: count_withdraw_total
    common: count_withdraw_common
    senior: count_withdraw_senior
    finance: count_withdraw_finance
  profit:
    total: count_profit_tatal
    recommend: count_profit_recommend
    view: count_profit_view
    member: count_profit_member

todo:
  recharge-count: todo_recharge_count
  withdraw-count: todo_withdraw_count
#recharge:
#  todolist: recharge_todo_list
#  donelist: recharge_done_list
#  invalidlist: recharge_invalid_list
#analysis:
#  user:
#  action:
